"""Generator for environment setup validation script."""

from loom.config import LoomConfig


def generate_env_setup(config: LoomConfig) -> str:
    """Generate .claude/env-setup.sh to validate environment.

    Returns bash script that checks all shared_env variables are set
    and optionally runs per-repo doctor commands.

    Args:
        config: LoomConfig

    Returns:
        str: Bash script content for env-setup.sh
    """
    lines = [
        "#!/bin/bash",
        "# Generated by loom — environment validation",
        "",
        "set -e",
        "",
        "MISSING=0",
        "",
    ]

    # Collect all shared env vars
    all_env_vars = set()
    for zone in config.impact_zones or []:
        if zone.shared_env:
            all_env_vars.update(zone.shared_env)

    if all_env_vars:
        lines.extend([
            "# Check required environment variables",
            "",
        ])

        for env_var in sorted(all_env_vars):
            lines.extend([
                f"if [ -z \"${{{env_var}}}\" ]; then",
                f"  echo \"[!] Missing: {env_var}\"",
                "  MISSING=$((MISSING + 1))",
                "else",
                f"  echo \"[✓] {env_var} is set\"",
                "fi",
            ])

        lines.extend([
            "",
            "if [ $MISSING -gt 0 ]; then",
            "  echo \"\"",
            "  echo \"[ERROR] $MISSING environment variable(s) not set.\"",
            "  echo \"\"",
            "  echo \"Required variables by impact zone:\"",
            "  echo \"\"",
        ])

        for zone in config.impact_zones or []:
            if zone.shared_env:
                lines.append(f"  echo \"  {zone.name} ({zone.id}):\"")
                for env_var in zone.shared_env:
                    lines.append(f"    echo \"    - {env_var}\"")

        lines.extend([
            "  exit 1",
            "fi",
            "",
        ])

    # Run doctor commands
    lines.extend([
        "# Run health checks (if doctor commands available)",
        "",
    ])

    for repo in config.repos:
        if repo.doctor_command:
            lines.extend([
                f"echo \"[*] Checking {repo.name}...\"",
                f"if [ -d \"services/{repo.name}\" ]; then",
                f"  (cd services/{repo.name} && {repo.doctor_command} || echo \"[!] Doctor check failed\")",
                "fi",
                "",
            ])

    lines.extend([
        "echo \"\"",
        "echo \"[✓] Environment setup complete\"",
    ])

    return "\n".join(lines)
